sudo: true

cache:
  directories:
  - node_modules

notifications:
  email: false

install:
  - npm i -g npm
  - npm install --only=dev
  - npm install

before_script:
  - npm prune

script:
  - npm run build

