sudo: true

notifications:
  email: false

language: node_js
node_js:
  - lts/*

install:
  - npm i -g npm
  - npm install --only=dev
  - npm install

before_script:
  - npm prune

script:
  - npm run build

deploy:
  provider: surge
  project: ./docs/
  domain: mrpt-web.surge.sh
